name: ci

on: [push, pull_request]

jobs:
  name: deno_std-${{ matrix.os }}
  runs-on: ${{ matrix.os }}
  timeout-minutes: 30
  strategy:
    matrix:
      os: [macOS-latest, ubuntu-latest, windows-2019]

  steps:
    - uses: actions/checkout@v2
    
    
    - name: 
    - run: |
        deno --version
        deno run https://deno.land/std/examples/welcome.ts
        deno install --allow-read -n deno_cat https://deno.land/std/examples/cat.ts
        deno_cat ./README.md
        
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: true
        persist-credentials: false

    - name: Install Deno
      uses: denolib/setup-deno@master
      with:
        deno-version: nightly

    - name: Format
      run: deno fmt --check

    - name: Lint
      run: deno lint --ignore=std/**/testdata,std/**/node_modules

    # - name: Lint
    #   run: deno test

