name: ci

on: [pull_request]

jobs:
  std:
    name: deno_std-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-2019]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: nightly

      - name: Format
        run: |
          deno fmt --check \
            --ignore=node/tests/node_modules \

      - name: Lint
        run: |
          deno lint --unstable \
            --ignore=node/tests/node_modules \

      # - name: Lint
      #   run: deno test

